version: '2.4'
services:
  envoy:
    build: 
      context: envoy
    ports:
    - 18080:18080
    - 9901:9901
    depends_on: 
    - server
  server:
    build: server
  web:
    build: .
    ports:
      - 8081:80
    depends_on: 
      - server
